import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image';
import axios from 'axios';
import { BsSearch } from 'react-icons/bs';

export default function Home() {

  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  
  const url = `https://api.openweathermap.org/data/2.5/weather?q=Barinas&units=metric&appid=${process.env.NEXT_PUBLIC_API_KEY}`;
  
  function fetchWeather (e){
    e.preventDefault();
    setLoading(true);
    axios.get(url).then( (response) => {
      setWeather(response.data)
      console.log(response.data)
    });
    setCity("")
    setLoading(false)
  }
   

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={fetchWeather}>fetch</button>
      
    </div>
  )
}
